site_name: semeval26_valence_arousal_from_text
nav:
  - Home: index.md

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      project_name: semeval26_valence_arousal_from_text
      handlers:
        python:
          options:
            docstring_style: numpy